config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :get_post, only: [:show, :edit, :update, :destroy]
	def index
      @posts = Post.all		
	end

	def new
      @post = Post.new
	end

	def create	
      @post = Post.new(post_params)
      @post.save
      redirect_to posts_path, notice: 'Post is successfully created'
    end

    def show
    end

    def edit
    end

    def update
     @post.update(post_params)
     redirect_to posts_path
    end

    def destroy
      @post.destroy
      redirect_to posts_path
    end

 private
   
   def post_params
     params.require(:post).permit(:name, :description)
   end

   def get_post
    @post = Post.find(params[:id])
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QuickBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.haml
= form_for @post do |f|
  = f.label :name 
  %br
  = f.text_field :name
  %br
  = f.label :description
  %br
  = f.text_area :description
  %br
  = f.submit
= link_to 'Posts', posts_path

app/views/posts/edit.html.haml
%h1 Edit Post
= render 'form'

app/views/posts/index.html.haml
%h1 Posts
%table
  %thead
    %tr
      %th Name
      %th Description
  %tbody
    - @posts.each do |post|
      %tr
        %td= post.name
        %td= post.description
        %td
          = link_to 'show', post_path(post)
        %td
          = link_to 'Edit', edit_post_path(post)
        %td
          = link_to 'Delete', post, method: :delete, data: {confirm: 'Are you sure?'}
= link_to 'New Post', new_post_path

app/views/posts/new.html.haml
%h1 New Post
= render 'form'

app/views/posts/show.html.haml
%p
  %h3 Name
  %br
  = @post.name
%p
  %h3 Description
  %br
  = @post.description